language: python
python:
  - "3.3"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - "cd api/v1"
  - "python manage.py databases init"
  - "python manage.py databases migrate"
  - "python manage.py databases upgrade"

script:
  - nosetests --cover-erase  --cover-package=. --with-coverage

after_success:
  - coveralls