language: python
python:
  - "3.3"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - nosetests --cover-erase  --cover-package=. --with-coverage
after_success:
  - coveralls