language: python
python:
  - "3.3"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install coverage"

before_script:
  - "cd api/v1"

script:
  - nosetests -v --cover-erase  --cover-package=. --with-coverage --cover-tests

after_success:
  - coveralls