language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - "cd api/v1"
  -"python mana

script:
  - nosetests -v --cover-erase  --cover-package=. --with-coverage --cover-tests

after_success:
  - coveralls